#-------------------------------
# General Site Settings

baseURL = 'https://yuricunha.com/'
languageCode = 'en-us'
title = 'Yuri Cunha'
theme = 'menca'
googleAnalytics = ""

[pagination]
  pagerSize = 9

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "snippets"
    name = "Snippets"
    url = "/snippets"
    weight = 2

  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 4

  [[menu.main]]
    identifier = "hardware"
    name = "Hardware"
    url = "/hardware"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 6


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "committing changes to my life database every day"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Yuri Cunha"
    author__bio = "database administrator, homelab owner, privacy advocate"
    author__avatar = "/images/avatar.png"

  [[params.social]]
    icon = "logo-github"
    name = "GitHub"
    link = "https://github.com/isyuricunha"

  [[params.social]]
    icon = "logo-linkedin"
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/isyuricunha"

  [[params.social]]
    icon = "logo-twitter"
    name = "Twitter/X"
    link = "https://x.com/isyuricunha"

  [[params.social]]
    icon = "logo-rss"
    name = "RSS"
    link = "/index.xml"


  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "hey, i'm yuri cunha"
    hero__description = "database administrator, homelab enthusiast, and privacy advocate. i build things that respect your data."
    hero__image = "/images/avatar.png"

  #-------------------------------
  # Gallery Footer Section
  [params.gallery]
    gallery__title = "what i work with"
    gallery__columns = 3

  [[params.gallery_image]]
    image_alt = "postgresql database"
    image_url = "/images/gallery-postgresql.png"

  [[params.gallery_image]]
    image_alt = "linux servers"
    image_url = "/images/gallery-linux.png"

  [[params.gallery_image]]
    image_alt = "docker containers"
    image_url = "/images/gallery-docker.png"

  [[params.gallery_image]]
    image_alt = "homelab setup"
    image_url = "/images/gallery-homelab.png"

  [[params.gallery_image]]
    image_alt = "privacy tools"
    image_url = "/images/gallery-privacy.png"

  [[params.gallery_image]]
    image_alt = "monitoring dashboards"
    image_url = "/images/gallery-monitoring.png"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "me@yuricunha.com"

    # NOTE
    # You can use Formspree service to handle contact form submissions
    # Just add your Formspree form ID here


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false


[outputs]
  home = ["HTML", "RSS", "JSON"]


# Permalinks configuration
[permalinks]
  posts = "/blog/:slug/"
  snippets = "/snippet/:slug/"
