title = "Yuri Cunha"
baseURL = 'https://yuricunha.com/'

# This is what goes in <html lang="">
languageCode = 'en-us'

# This defines how dates are formatted
defaultContentLanguage = "en-us"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes'
theme = "hugo-blog-awesome"

# modern way: pull in theme component as hugo module
#[module]
  # Uncomment the next line to build and serve using local theme clone declared in the named Hugo workspace:
  # workspace = "hugo-blog-awesome.work"
  #[module.hugoVersion]
    #extended = true
    #min = "0.87.0"
  #[[module.imports]]
    #path = "github.com/hugo-sid/hugo-blog-awesome"
    #disable = false

[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
  [services.googleAnalytics]
    id = '' # G-MEASUREMENT_ID

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next two lines
  [services.disqus]
    shortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[related]
  threshold = 50
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "keywords"
    weight = 50

  [[related.indices]]
    name = "date"
    weight = 10


[permalinks]
  [permalinks.page]
    pages = "/:slug/"
    posts = "/blog/:slug/"
    snippets = "/snippet/:slug/"
  [permalinks.section]
    posts = "/blog/"
    snippets = "/snippet/"

############################## English language ################################

[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/en"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef="blog"
    name = 'Blog'
    url = '/blog/'
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef="snippets"
    name = 'Snippets'
    url = '/snippet/'
    weight = 25
  [[Languages.en-us.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30
  [[Languages.en-us.menu.main]]
    pageRef="now"
    name = 'Now'
    url = '/now/'
    weight = 35
    [[Languages.en-us.menu.main]]
    pageRef="contact"
    name = 'Contact'
    url = '/contact/'
    weight = 40
  [[Languages.en-us.menu.main]]
    pageRef="hardware"
    name = 'Hardware'
    url = '/hardware/'
    weight = 40
  [[Languages.en-us.menu.main]]
    pageRef="projects"
    name = 'Projects'
    url = '/projects/'
    weight = 45

[Languages.en-us.params]
  sitename = "Yuri Cunha"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "committing changes to my life database every day"
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js', 'js/copy-code.js', 'js/reading-progress.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/time/format/ for available date formats.
  rssFeedDescription = "full" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.en-us.params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Yuri Cunha"
  name = "Yuri Cunha"
  description = "committing changes to my life database every day"

# Allow to override webmanifest options
[Languages.en-us.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#f59e0b" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#000000ff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#f59e0b" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/isyuricunha"

[[params.socialIcons]]
name = "x"
url = "https://x.com/isyuricunha"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
