#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Menca"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 9


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "programming"
    name = "Programming"
    url = "/programming"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

  [[menu.main]]
    identifier = "elements"
    name = "Elements"
    url = "/elements"
    weight = 4


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Menca personal blogging theme for HUGO"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Camelia Mendes"
    author__bio = "Designs, talks, and writes about web, ethics, privacy, and dev. I share design tutorials, free resources and inspiration."
    author__avatar = "https://via.placeholder.com/200x200"

  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Hey, Iâ€™m Camelia Mendes"
    hero__description = "Designs, talks, and writes about web, ethics, privacy, and dev. I share design tutorials, free resources and inspiration."
    hero__image = "https://via.placeholder.com/1200x800"

  # Newsletter
  # [params.mailchimp]
    # mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    # mailchimp__input__text = "Subscribe here"
    # mailchimp__button__text = "Get a new tip"


  #-------------------------------
  # Gallery Footer Section
  [params.gallery]
    gallery__title = "Gallery"
    gallery__columns = 3 # You can change the number of gallery columns

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Lifestyle"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Hobby"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Notes"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Hobby"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Fashion"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Notes"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x600"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your email for contant form

    # NOTE
    # Menca comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  # [params.disqus]
  #  disqusShortname = "demo-menca" # Add your shortname for Disqus Comment. For example demo-menca


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
